[project]
name = "flappy-bird"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mikhail Sumygin", email = "mikhailsumygin@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "pygame>=2.6.1",
]

[project.scripts]
flappy-bird = "flappy_bird:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
